#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<float,16> float16;
typedef hls::vector<float,8> float8;
typedef hls::vector<float,4> float4;
typedef hls::vector<float,2> float2;



void kernel_nlp(float val[256][7], float x[262], float y[256]) {

    int i;
    int j;
    for ( i = 0; i < 256; i++) {
        y[i] = 0;
    }
    for ( i = 0; i < 256; i++) {
        for ( j = 0; j < 7; j++) {
            y[i] = y[i] + val[i][j] * x[i + j];
        }
    }
}
