#include "output_2.h"

#define READ_RANGE(Arr, data_size, l) (Arr.data.range((data_size)*(l) + (data_size)-1, (data_size)*(l)))


/****************************************************
 This file was automatically generated by Prometheus
****************************************************/
void load_vy_for_task1(hls::stream<float1>& fifo_y_from_off_chip_to_S1, float1 vy[400]){
#pragma HLS inline off
    for (int i = 0; i < 400; i++){
    #pragma HLS pipeline II=1
        fifo_y_from_off_chip_to_S1.write(vy[i]);
    }
}

void load_vx_for_task1(hls::stream<float1>& fifo_x_from_off_chip_to_S1, float1 vx[400]){
#pragma HLS inline off
    for (int i = 0; i < 400; i++){
    #pragma HLS pipeline II=1
        fifo_x_from_off_chip_to_S1.write(vx[i]);
    }
}

void load_vw_for_task3(hls::stream<float1>& fifo_w_from_off_chip_to_S3, float1 vw[400]){
#pragma HLS inline off
    for (int i = 0; i < 400; i++){
    #pragma HLS pipeline II=1
        fifo_w_from_off_chip_to_S3.write(vw[i]);
    }
}

void load_ve1_for_task0(hls::stream<float1>& fifo_e1_from_off_chip_to_S0, float1 ve1[400]){
#pragma HLS inline off
    for (int i = 0; i < 400; i++){
    #pragma HLS pipeline II=1
        fifo_e1_from_off_chip_to_S0.write(ve1[i]);
    }
}

void load_ve2_for_task0(hls::stream<float1>& fifo_e2_from_off_chip_to_S0, float1 ve2[400]){
#pragma HLS inline off
    for (int i = 0; i < 400; i++){
    #pragma HLS pipeline II=1
        fifo_e2_from_off_chip_to_S0.write(ve2[i]);
    }
}

void load_vu1_for_task0(hls::stream<float1>& fifo_u1_from_off_chip_to_S0, float1 vu1[400]){
#pragma HLS inline off
    for (int i = 0; i < 400; i++){
    #pragma HLS pipeline II=1
        fifo_u1_from_off_chip_to_S0.write(vu1[i]);
    }
}

void load_vA_for_task0(hls::stream<float1>& fifo_A_from_off_chip_to_S0, float1 vA[160000]){
#pragma HLS inline off
    for (int i = 0; i < 160000; i++){
    #pragma HLS pipeline II=1
        fifo_A_from_off_chip_to_S0.write(vA[i]);
    }
}

void load_vu2_for_task0(hls::stream<float1>& fifo_u2_from_off_chip_to_S0, float1 vu2[400]){
#pragma HLS inline off
    for (int i = 0; i < 400; i++){
    #pragma HLS pipeline II=1
        fifo_u2_from_off_chip_to_S0.write(vu2[i]);
    }
}

void load_vz_for_task2(hls::stream<float1>& fifo_z_from_off_chip_to_S2, float1 vz[400]){
#pragma HLS inline off
    for (int i = 0; i < 400; i++){
    #pragma HLS pipeline II=1
        fifo_z_from_off_chip_to_S2.write(vz[i]);
    }
}

void store_vx_for_task1(hls::stream<float1>& fifo_x_to_off_chip, float1 vx[400]){
#pragma HLS inline off
    for (int i = 0; i < 400; i++){
    #pragma HLS pipeline II=1
        vx[i] = fifo_x_to_off_chip.read();
    }
}

void store_vw_for_task3(hls::stream<float1>& fifo_w_to_off_chip, float1 vw[400]){
#pragma HLS inline off
    for (int i = 0; i < 400; i++){
    #pragma HLS pipeline II=1
        vw[i] = fifo_w_to_off_chip.read();
    }
}

void store_vA_for_task0(hls::stream<float1>& fifo_A_to_off_chip, float1 vA[160000]){
#pragma HLS inline off
    for (int i = 0; i < 160000; i++){
    #pragma HLS pipeline II=1
        vA[i] = fifo_A_to_off_chip.read();
    }
}

void FT0_level0(float alpha, float beta, hls::stream<float1>& fifo_A_from_task0_to_task1, hls::stream<float1>& fifo_A_from_task0_to_task3, hls::stream<float1>& fifo_e1_from_off_chip_to_S0, hls::stream<float1>& fifo_e2_from_off_chip_to_S0, hls::stream<float1>& fifo_u1_from_off_chip_to_S0, hls::stream<float1>& fifo_A_from_off_chip_to_S0, hls::stream<float1>& fifo_u2_from_off_chip_to_S0, hls::stream<float1>& fifo_A_to_off_chip){
#pragma HLS inline off
    for (int i0 = 0; i0 < 0; i0++) {

if (i0 % 2 == 0){ 
        FT0_level1(alpha, beta, fifo_A_from_task0_to_task1, fifo_A_from_task0_to_task3, fifo_e1_from_off_chip_to_S0, fifo_e2_from_off_chip_to_S0, fifo_u1_from_off_chip_to_S0, fifo_A_from_off_chip_to_S0, fifo_u2_from_off_chip_to_S0, fifo_A_to_off_chip, i0);
    }
else if (i0 % 2 == 1){  
        FT0_level1(alpha, beta, fifo_A_from_task0_to_task1, fifo_A_from_task0_to_task3, fifo_e1_from_off_chip_to_S0, fifo_e2_from_off_chip_to_S0, fifo_u1_from_off_chip_to_S0, fifo_A_from_off_chip_to_S0, fifo_u2_from_off_chip_to_S0, fifo_A_to_off_chip, i0);
    }
    }
}
void compute_FT0_level1(float alpha,  float beta,  hls::stream<float1>& fifo_A_from_task0_to_task1,  hls::stream<float1>& fifo_A_from_task0_to_task3,  hls::stream<float1>& fifo_e1_from_off_chip_to_S0,  hls::stream<float1>& fifo_e2_from_off_chip_to_S0,  hls::stream<float1>& fifo_u1_from_off_chip_to_S0,  hls::stream<float1>& fifo_A_from_off_chip_to_S0,  hls::stream<float1>& fifo_u2_from_off_chip_to_S0,  hls::stream<float1>& fifo_A_to_off_chip,  int i0, int j0, float A_0[400][400],float A_1[400][400],float A_2[400][400]) {
#pragma HLS inline off
#pragma HLS dataflow
    read_A_FT0(A_0, fifo_A_from_off_chip_to_S0, j0+1, i0);
    task0_intra(alpha, beta, i0, A_1, j0);
    write_A_FT0(A_2, fifo_A_from_task0_to_task1, j0-1, i0);
    write_A_FT0(A_2, fifo_A_from_task0_to_task3, j0-1, i0);
    write_A_FT0(A_2, fifo_A_to_off_chip, j0-1, i0);
}

void FT0_level1(float alpha, float beta, hls::stream<float1>& fifo_A_from_task0_to_task1, hls::stream<float1>& fifo_A_from_task0_to_task3, hls::stream<float1>& fifo_e1_from_off_chip_to_S0, hls::stream<float1>& fifo_e2_from_off_chip_to_S0, hls::stream<float1>& fifo_u1_from_off_chip_to_S0, hls::stream<float1>& fifo_A_from_off_chip_to_S0, hls::stream<float1>& fifo_u2_from_off_chip_to_S0, hls::stream<float1>& fifo_A_to_off_chip, int i0){
#pragma HLS inline off
    float A_0[400][400];
 // FT0 
#pragma HLS array_partition variable=A_0 cyclic factor=0 dim=1 
    float A_1[400][400];
 // FT0 
#pragma HLS array_partition variable=A_1 cyclic factor=0 dim=1 
    float A_2[400][400];
 // FT0 
#pragma HLS array_partition variable=A_2 cyclic factor=0 dim=1 
    read_A_FT0(A_0, fifo_A_from_off_chip_to_S0, 0, i0);
        for (int j0 = 0; j0 < 0; j0++) {
if (j0 % 3 == 0){ 
//     read_A_FT0(A_1, fifo_A_from_off_chip_to_S0, j0+1, i0);
//     task0_intra(alpha, beta, i0, A_0, j0);
//     write_A_FT0(A_2, fifo_A_from_task0_to_task1, j0-1, i0);
//     write_A_FT0(A_2, fifo_A_from_task0_to_task3, j0-1, i0);
//     write_A_FT0(A_2, fifo_A_to_off_chip, j0-1, i0);
compute_FT0_level1(alpha, beta, fifo_A_from_task0_to_task1, fifo_A_from_task0_to_task3, fifo_e1_from_off_chip_to_S0, fifo_e2_from_off_chip_to_S0, fifo_u1_from_off_chip_to_S0, fifo_A_from_off_chip_to_S0, fifo_u2_from_off_chip_to_S0, fifo_A_to_off_chip, i0,  j0, A_1, A_0, A_2); 
    }
else if (j0 % 3 == 1){  
//     read_A_FT0(A_2, fifo_A_from_off_chip_to_S0, j0+1, i0);
//     task0_intra(alpha, beta, i0, A_1, j0);
//     write_A_FT0(A_0, fifo_A_from_task0_to_task1, j0-1, i0);
//     write_A_FT0(A_0, fifo_A_from_task0_to_task3, j0-1, i0);
//     write_A_FT0(A_0, fifo_A_to_off_chip, j0-1, i0);
compute_FT0_level1(alpha, beta, fifo_A_from_task0_to_task1, fifo_A_from_task0_to_task3, fifo_e1_from_off_chip_to_S0, fifo_e2_from_off_chip_to_S0, fifo_u1_from_off_chip_to_S0, fifo_A_from_off_chip_to_S0, fifo_u2_from_off_chip_to_S0, fifo_A_to_off_chip, i0,  j0, A_2, A_1, A_0); 
    }
else if (j0 % 3 == 2){  
//     read_A_FT0(A_0, fifo_A_from_off_chip_to_S0, j0+1, i0);
//     task0_intra(alpha, beta, i0, A_2, j0);
//     write_A_FT0(A_1, fifo_A_from_task0_to_task1, j0-1, i0);
//     write_A_FT0(A_1, fifo_A_from_task0_to_task3, j0-1, i0);
//     write_A_FT0(A_1, fifo_A_to_off_chip, j0-1, i0);
compute_FT0_level1(alpha, beta, fifo_A_from_task0_to_task1, fifo_A_from_task0_to_task3, fifo_e1_from_off_chip_to_S0, fifo_e2_from_off_chip_to_S0, fifo_u1_from_off_chip_to_S0, fifo_A_from_off_chip_to_S0, fifo_u2_from_off_chip_to_S0, fifo_A_to_off_chip, i0,  j0, A_0, A_2, A_1); 
    }
        }
    write_A_FT0(A_2, fifo_A_from_task0_to_task1, -1, i0);
    write_A_FT0(A_2, fifo_A_from_task0_to_task3, -1, i0);
    write_A_FT0(A_2, fifo_A_to_off_chip, -1, i0);
}
void compute_FT1_level0(float alpha,  float beta,  hls::stream<float1>& fifo_A_from_task0_to_task1,  hls::stream<float1>& fifo_y_from_off_chip_to_S1,  hls::stream<float1>& fifo_x_from_off_chip_to_S1,  hls::stream<float1>& fifo_x_from_task2_to_task3,  hls::stream<float1>& fifo_z_from_off_chip_to_S2,  hls::stream<float1>& fifo_x_to_off_chip, int i0, float x_0[400],float x_1[400],float x_2[400],float y[400]) {
#pragma HLS inline off
#pragma HLS dataflow
    read_x_FT1(x_0, fifo_x_from_off_chip_to_S1, i0+1);
    task1_intra(alpha, beta, x_1, y, i0);
    task2_intra(alpha, beta, x_1, y, i0);
    write_x_FT1(x_2, fifo_x_from_task2_to_task3, i0-1);
    write_x_FT1(x_2, fifo_x_to_off_chip, i0-1);
}

void FT1_level0(float alpha, float beta, hls::stream<float1>& fifo_A_from_task0_to_task1, hls::stream<float1>& fifo_y_from_off_chip_to_S1, hls::stream<float1>& fifo_x_from_off_chip_to_S1, hls::stream<float1>& fifo_x_from_task2_to_task3, hls::stream<float1>& fifo_z_from_off_chip_to_S2, hls::stream<float1>& fifo_x_to_off_chip){
#pragma HLS inline off
    float x_0[400];
 // FT1 
#pragma HLS array_partition variable=x_0 cyclic factor=0 dim=1 
    float x_1[400];
 // FT1 
#pragma HLS array_partition variable=x_1 cyclic factor=0 dim=1 
    float x_2[400];
 // FT1 
#pragma HLS array_partition variable=x_2 cyclic factor=0 dim=1 
    float y[400];
#pragma HLS array_partition variable=y cyclic factor=0 dim=1 
    read_y_FT1(y, fifo_y_from_off_chip_to_S1);
    read_x_FT1(x_0, fifo_x_from_off_chip_to_S1, 0);
    for (int i0 = 0; i0 < 0; i0++) {
if (i0 % 3 == 0){ 
//     read_x_FT1(x_1, fifo_x_from_off_chip_to_S1, i0+1);
//     task1_intra(alpha, beta, x_0, y, i0);
//     task2_intra(alpha, beta, x_0, y, i0);
//     write_x_FT1(x_2, fifo_x_from_task2_to_task3, i0-1);
//     write_x_FT1(x_2, fifo_x_to_off_chip, i0-1);
compute_FT1_level0(alpha, beta, fifo_A_from_task0_to_task1, fifo_y_from_off_chip_to_S1, fifo_x_from_off_chip_to_S1, fifo_x_from_task2_to_task3, fifo_z_from_off_chip_to_S2, fifo_x_to_off_chip,  i0, x_1, x_0, x_2, y); 
    }
else if (i0 % 3 == 1){  
//     read_x_FT1(x_2, fifo_x_from_off_chip_to_S1, i0+1);
//     task1_intra(alpha, beta, x_1, y, i0);
//     task2_intra(alpha, beta, x_1, y, i0);
//     write_x_FT1(x_0, fifo_x_from_task2_to_task3, i0-1);
//     write_x_FT1(x_0, fifo_x_to_off_chip, i0-1);
compute_FT1_level0(alpha, beta, fifo_A_from_task0_to_task1, fifo_y_from_off_chip_to_S1, fifo_x_from_off_chip_to_S1, fifo_x_from_task2_to_task3, fifo_z_from_off_chip_to_S2, fifo_x_to_off_chip,  i0, x_2, x_1, x_0, y); 
    }
else if (i0 % 3 == 2){  
//     read_x_FT1(x_0, fifo_x_from_off_chip_to_S1, i0+1);
//     task1_intra(alpha, beta, x_2, y, i0);
//     task2_intra(alpha, beta, x_2, y, i0);
//     write_x_FT1(x_1, fifo_x_from_task2_to_task3, i0-1);
//     write_x_FT1(x_1, fifo_x_to_off_chip, i0-1);
compute_FT1_level0(alpha, beta, fifo_A_from_task0_to_task1, fifo_y_from_off_chip_to_S1, fifo_x_from_off_chip_to_S1, fifo_x_from_task2_to_task3, fifo_z_from_off_chip_to_S2, fifo_x_to_off_chip,  i0, x_0, x_2, x_1, y); 
    }
    }
    write_x_FT1(x_2, fifo_x_from_task2_to_task3, -1);
    write_x_FT1(x_2, fifo_x_to_off_chip, -1);
}
void compute_FT2_level0(float alpha,  float beta,  hls::stream<float1>& fifo_A_from_task0_to_task3,  hls::stream<float1>& fifo_x_from_task2_to_task3,  hls::stream<float1>& fifo_w_from_off_chip_to_S3,  hls::stream<float1>& fifo_w_to_off_chip, int i0, float w_0[400],float w_1[400],float w_2[400],float x[400]) {
#pragma HLS inline off
#pragma HLS dataflow
    read_w_FT2(w_0, fifo_w_from_off_chip_to_S3, i0+1);
    task3_intra(alpha, beta, w_1, x, i0);
    write_w_FT2(w_2, fifo_w_to_off_chip, i0-1);
}

void FT2_level0(float alpha, float beta, hls::stream<float1>& fifo_A_from_task0_to_task3, hls::stream<float1>& fifo_x_from_task2_to_task3, hls::stream<float1>& fifo_w_from_off_chip_to_S3, hls::stream<float1>& fifo_w_to_off_chip){
#pragma HLS inline off
    float w_0[400];
 // FT2 
#pragma HLS array_partition variable=w_0 cyclic factor=0 dim=1 
    float w_1[400];
 // FT2 
#pragma HLS array_partition variable=w_1 cyclic factor=0 dim=1 
    float w_2[400];
 // FT2 
#pragma HLS array_partition variable=w_2 cyclic factor=0 dim=1 
    float x[400];
#pragma HLS array_partition variable=x cyclic factor=0 dim=1 
    read_x_FT2(x, fifo_x_from_task2_to_task3);
    read_w_FT2(w_0, fifo_w_from_off_chip_to_S3, 0);
    for (int i0 = 0; i0 < 0; i0++) {
if (i0 % 3 == 0){ 
//     read_w_FT2(w_1, fifo_w_from_off_chip_to_S3, i0+1);
//     task3_intra(alpha, beta, w_0, x, i0);
//     write_w_FT2(w_2, fifo_w_to_off_chip, i0-1);
compute_FT2_level0(alpha, beta, fifo_A_from_task0_to_task3, fifo_x_from_task2_to_task3, fifo_w_from_off_chip_to_S3, fifo_w_to_off_chip,  i0, w_1, w_0, w_2, x); 
    }
else if (i0 % 3 == 1){  
//     read_w_FT2(w_2, fifo_w_from_off_chip_to_S3, i0+1);
//     task3_intra(alpha, beta, w_1, x, i0);
//     write_w_FT2(w_0, fifo_w_to_off_chip, i0-1);
compute_FT2_level0(alpha, beta, fifo_A_from_task0_to_task3, fifo_x_from_task2_to_task3, fifo_w_from_off_chip_to_S3, fifo_w_to_off_chip,  i0, w_2, w_1, w_0, x); 
    }
else if (i0 % 3 == 2){  
//     read_w_FT2(w_0, fifo_w_from_off_chip_to_S3, i0+1);
//     task3_intra(alpha, beta, w_2, x, i0);
//     write_w_FT2(w_1, fifo_w_to_off_chip, i0-1);
compute_FT2_level0(alpha, beta, fifo_A_from_task0_to_task3, fifo_x_from_task2_to_task3, fifo_w_from_off_chip_to_S3, fifo_w_to_off_chip,  i0, w_0, w_2, w_1, x); 
    }
    }
    write_w_FT2(w_2, fifo_w_to_off_chip, -1);
}
void task0_intra(float alpha, float beta, int i0, float A[400][400], int j0){
#pragma HLS inline off
    int i;
    int j;
i=i0*0+i1;
A[i][j]=A[i][j]+u1[i]*e1[j]+u2[i]*e2[j];
}


void task1_intra(float alpha, float beta, float x[400], float y[400], int i0){
#pragma HLS inline off
    int i;
    int j;
        for (int j0 = 0; j0 < 0; j0++) {
#pragma HLS pipeline II=2
            for (int i1 = 0; i1 < 0; i1++) {
#pragma HLS unroll
                for (int j1 = 0; j1 < 0; j1++) {
#pragma HLS unroll
                    i = i0 * 0 + i1;
                    j = j0 * 0 + j1;
x[i]=x[i]+beta*A[j][i]*y[j];
                }
            }
        }
}


void task2_intra(float alpha, float beta, float x[400], float y[400], int i0){
#pragma HLS inline off
    int i;
        for (int i1 = 0; i1 < 0; i1++) {
#pragma HLS unroll
            i = i0 * 0 + i1;
x[i]=x[i]+z[i];
        }
}


void task3_intra(float alpha, float beta, float w[400], float x[400], int i0){
#pragma HLS inline off
    int i;
    int j;
        for (int j0 = 0; j0 < 0; j0++) {
#pragma HLS pipeline II=2
            for (int i1 = 0; i1 < 0; i1++) {
#pragma HLS unroll
                for (int j1 = 0; j1 < 0; j1++) {
#pragma HLS unroll
                    i = i0 * 0 + i1;
                    j = j0 * 0 + j1;
w[i]=w[i]+alpha*A[i][j]*x[j];
                }
            }
        }
}


void read_A_FT0(float A[400][400], hls::stream<float1>& fifo_A_from_off_chip_to_S0, int j0, int i0){
#pragma HLS inline off
if (i0 >= 0||j0 >= 0) {
return;
}
    for (int d0 = 0; d0 < 400; d0++){
        for (int d1 = 0; d1 < 400; d1+=1){
        #pragma HLS pipeline II=1
float1 tmp_fifo = fifo_A_from_off_chip_to_S0.read();
            A[d0 + 0][d1 + 0 + 0] = tmp_fifo[0];
        }
    }
}

void read_y_FT1(float y[400], hls::stream<float1>& fifo_y_from_off_chip_to_S1){
#pragma HLS inline off
    for (int d0 = 0; d0 < 400; d0+=1){
    #pragma HLS pipeline II=1
float1 tmp_fifo = fifo_y_from_off_chip_to_S1.read();
        y[d0 + 0 + 0] = tmp_fifo[0];
    }
}

void read_x_FT1(float x[400], hls::stream<float1>& fifo_x_from_off_chip_to_S1, int i0){
#pragma HLS inline off
if (i0 >= 0) {
return;
}
    for (int d0 = 0; d0 < 400; d0+=1){
    #pragma HLS pipeline II=1
float1 tmp_fifo = fifo_x_from_off_chip_to_S1.read();
        x[d0 + 0 + 0] = tmp_fifo[0];
    }
}

void read_x_FT2(float x[400], hls::stream<float1>& fifo_x_from_task2_to_task3){
#pragma HLS inline off
    for (int d0_0 = 0; d0_0 < 0; d0_0++){ 

    for (int d0_1 = 0; d0_1 <  0; d0_1+=1){  

int d0 = d0_0 * 0 + d0_1;
float1 tmp_fifo = fifo_x_from_task2_to_task3.read();
if (d0 + 0 < 400)
    x[d0 + 0 + 0] = tmp_fifo[0];
}
}
}

void read_w_FT2(float w[400], hls::stream<float1>& fifo_w_from_off_chip_to_S3, int i0){
#pragma HLS inline off
if (i0 >= 0) {
return;
}
    for (int d0 = 0; d0 < 400; d0+=1){
    #pragma HLS pipeline II=1
float1 tmp_fifo = fifo_w_from_off_chip_to_S3.read();
        w[d0 + 0 + 0] = tmp_fifo[0];
    }
}

void write_A_FT0(float A[400][400], hls::stream<float1>& fifo_A_from_task0_to_task1, int j0, int i0){
#pragma HLS inline off
if (j0 < 0||i0 < 0) {
return;
}
    for (int d0 = 0; d0 < 400; d0++){
        for (int d1 = 0; d1 < 400; d1+=1){
        #pragma HLS pipeline II=1
float1 tmp_fifo;
tmp_fifo[0] =             A[d0 + 0][d1 + 0 + 0];
fifo_A_from_task0_to_task1.write(tmp_fifo);
        }
    }
}

void write_x_FT1(float x[400], hls::stream<float1>& fifo_x_from_task2_to_task3, int i0){
#pragma HLS inline off
if (i0 < 0) {
return;
}
    for (int d0 = 0; d0 < 400; d0+=1){
    #pragma HLS pipeline II=1
float1 tmp_fifo;
tmp_fifo[0] =         x[d0 + 0 + 0];
fifo_x_from_task2_to_task3.write(tmp_fifo);
    }
}

void write_w_FT2(float w[400], hls::stream<float1>& fifo_w_to_off_chip, int i0){
#pragma HLS inline off
if (i0 < 0) {
return;
}
    for (int d0 = 0; d0 < 400; d0+=1){
    #pragma HLS pipeline II=1
float1 tmp_fifo;
tmp_fifo[0] =         w[d0 + 0 + 0];
fifo_w_to_off_chip.write(tmp_fifo);
    }
}


//extern "C"{
void kernel_nlp(float alpha, float beta, float1 vA_for_task0[160000], float1 vu1_for_task0[400], float1 ve1_for_task0[400], float1 vu2_for_task0[400], float1 ve2_for_task0[400], float1 vx_for_task1[400], float1 vy_for_task1[400], float1 vz_for_task2[400], float1 vw_for_task3[400]) {

#pragma HLS INTERFACE m_axi port=alpha offset=slave bundle=kernel_alpha
#pragma HLS INTERFACE m_axi port=beta offset=slave bundle=kernel_beta
#pragma HLS INTERFACE m_axi port=vA_for_task0 offset=slave bundle=kernel_vA_for_task0
#pragma HLS INTERFACE m_axi port=vu1_for_task0 offset=slave bundle=kernel_vu1_for_task0
#pragma HLS INTERFACE m_axi port=ve1_for_task0 offset=slave bundle=kernel_ve1_for_task0
#pragma HLS INTERFACE m_axi port=vu2_for_task0 offset=slave bundle=kernel_vu2_for_task0
#pragma HLS INTERFACE m_axi port=ve2_for_task0 offset=slave bundle=kernel_ve2_for_task0
#pragma HLS INTERFACE m_axi port=vx_for_task1 offset=slave bundle=kernel_vx_for_task1
#pragma HLS INTERFACE m_axi port=vy_for_task1 offset=slave bundle=kernel_vy_for_task1
#pragma HLS INTERFACE m_axi port=vz_for_task2 offset=slave bundle=kernel_vz_for_task2
#pragma HLS INTERFACE m_axi port=vw_for_task3 offset=slave bundle=kernel_vw_for_task3
#pragma HLS INTERFACE s_axilite port=alpha bundle=control
#pragma HLS INTERFACE s_axilite port=beta bundle=control
#pragma HLS INTERFACE s_axilite port=vA_for_task0 bundle=control
#pragma HLS INTERFACE s_axilite port=vu1_for_task0 bundle=control
#pragma HLS INTERFACE s_axilite port=ve1_for_task0 bundle=control
#pragma HLS INTERFACE s_axilite port=vu2_for_task0 bundle=control
#pragma HLS INTERFACE s_axilite port=ve2_for_task0 bundle=control
#pragma HLS INTERFACE s_axilite port=vx_for_task1 bundle=control
#pragma HLS INTERFACE s_axilite port=vy_for_task1 bundle=control
#pragma HLS INTERFACE s_axilite port=vz_for_task2 bundle=control
#pragma HLS INTERFACE s_axilite port=vw_for_task3 bundle=control
#pragma HLS DATA_PACK VARIABLE=alpha
#pragma HLS DATA_PACK VARIABLE=beta
#pragma HLS DATA_PACK VARIABLE=vA_for_task0
#pragma HLS DATA_PACK VARIABLE=vu1_for_task0
#pragma HLS DATA_PACK VARIABLE=ve1_for_task0
#pragma HLS DATA_PACK VARIABLE=vu2_for_task0
#pragma HLS DATA_PACK VARIABLE=ve2_for_task0
#pragma HLS DATA_PACK VARIABLE=vx_for_task1
#pragma HLS DATA_PACK VARIABLE=vy_for_task1
#pragma HLS DATA_PACK VARIABLE=vz_for_task2
#pragma HLS DATA_PACK VARIABLE=vw_for_task3
#pragma HLS INTERFACE s_axilite port=return bundle=control

#pragma HLS dataflow

    hls::stream<float1> fifo_A_from_task0_to_task1;
    #pragma HLS stream variable=fifo_A_from_task0_to_task1 depth=512
    hls::stream<float1> fifo_y_from_off_chip_to_S1;
    #pragma HLS stream variable=fifo_y_from_off_chip_to_S1 depth=512
    hls::stream<float1> fifo_x_from_off_chip_to_S1;
    #pragma HLS stream variable=fifo_x_from_off_chip_to_S1 depth=512
    hls::stream<float1> fifo_A_from_task0_to_task3;
    #pragma HLS stream variable=fifo_A_from_task0_to_task3 depth=512
    hls::stream<float1> fifo_x_from_task2_to_task3;
    #pragma HLS stream variable=fifo_x_from_task2_to_task3 depth=512
    hls::stream<float1> fifo_w_from_off_chip_to_S3;
    #pragma HLS stream variable=fifo_w_from_off_chip_to_S3 depth=512
    hls::stream<float1> fifo_e1_from_off_chip_to_S0;
    #pragma HLS stream variable=fifo_e1_from_off_chip_to_S0 depth=512
    hls::stream<float1> fifo_e2_from_off_chip_to_S0;
    #pragma HLS stream variable=fifo_e2_from_off_chip_to_S0 depth=512
    hls::stream<float1> fifo_u1_from_off_chip_to_S0;
    #pragma HLS stream variable=fifo_u1_from_off_chip_to_S0 depth=512
    hls::stream<float1> fifo_A_from_off_chip_to_S0;
    #pragma HLS stream variable=fifo_A_from_off_chip_to_S0 depth=512
    hls::stream<float1> fifo_u2_from_off_chip_to_S0;
    #pragma HLS stream variable=fifo_u2_from_off_chip_to_S0 depth=512
    hls::stream<float1> fifo_z_from_off_chip_to_S2;
    #pragma HLS stream variable=fifo_z_from_off_chip_to_S2 depth=512
    hls::stream<float1> fifo_x_to_off_chip;
    #pragma HLS stream variable=fifo_x_to_off_chip depth=512
    hls::stream<float1> fifo_w_to_off_chip;
    #pragma HLS stream variable=fifo_w_to_off_chip depth=512
    hls::stream<float1> fifo_A_to_off_chip;
    #pragma HLS stream variable=fifo_A_to_off_chip depth=512

    load_vy_for_task1(fifo_y_from_off_chip_to_S1, vy_for_task1);
    load_vx_for_task1(fifo_x_from_off_chip_to_S1, vx_for_task1);
    load_vw_for_task3(fifo_w_from_off_chip_to_S3, vw_for_task3);
    load_ve1_for_task0(fifo_e1_from_off_chip_to_S0, ve1_for_task0);
    load_ve2_for_task0(fifo_e2_from_off_chip_to_S0, ve2_for_task0);
    load_vu1_for_task0(fifo_u1_from_off_chip_to_S0, vu1_for_task0);
    load_vA_for_task0(fifo_A_from_off_chip_to_S0, vA_for_task0);
    load_vu2_for_task0(fifo_u2_from_off_chip_to_S0, vu2_for_task0);
    load_vz_for_task2(fifo_z_from_off_chip_to_S2, vz_for_task2);

    FT0_level0(alpha, beta, fifo_A_from_task0_to_task1, fifo_A_from_task0_to_task3, fifo_e1_from_off_chip_to_S0, fifo_e2_from_off_chip_to_S0, fifo_u1_from_off_chip_to_S0, fifo_A_from_off_chip_to_S0, fifo_u2_from_off_chip_to_S0, fifo_A_to_off_chip);
    FT1_level0(alpha, beta, fifo_A_from_task0_to_task1, fifo_y_from_off_chip_to_S1, fifo_x_from_off_chip_to_S1, fifo_x_from_task2_to_task3, fifo_z_from_off_chip_to_S2, fifo_x_to_off_chip);
    FT2_level0(alpha, beta, fifo_A_from_task0_to_task3, fifo_x_from_task2_to_task3, fifo_w_from_off_chip_to_S3, fifo_w_to_off_chip);

    store_vx_for_task1(fifo_x_to_off_chip, vx_for_task1);
    store_vw_for_task3(fifo_w_to_off_chip, vw_for_task3);
    store_vA_for_task0(fifo_A_to_off_chip, vA_for_task0);
}
//}
