#include "output.h"

#define READ_RANGE(Arr, data_size, l) (Arr.data.range((data_size)*(l) + (data_size)-1, (data_size)*(l)))


/****************************************************
 This file was automatically generated by Prometheus
****************************************************/

void kernel_nlp_slr2(){
#pragma HLS interface ap_ctrl_none port=return
#pragma HLS inline off
}

