#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<float,16> float16;
typedef hls::vector<float,8> float8;
typedef hls::vector<float,4> float4;
typedef hls::vector<float,2> float2;



void kernel_nlp(float A[400][400], float u1[400], float e1[400], float u2[400], float e2[400], float w[400], float x[400], float y[400], float z[400]) {

    int j;
    int i;
#pragma scop
    for ( i = 0; i < 400; i++) {
        for ( j = 0; j < 400; j++) {
            A[i][j] = A[i][j] + u1[i] * e1[j] + u2[i] * e2[j];
        }
    }
    for ( i = 0; i < 400; i++) {
        for ( j = 0; j < 400; j++) {
            x[i] = x[i] + beta * A[j][i] * y[j];
        }
    }
    for ( i = 0; i < 400; i++) {
        x[i] = x[i] + z[i];
    }
    for ( i = 0; i < 400; i++) {
        for ( j = 0; j < 400; j++) {
            w[i] = w[i] + alpha * A[i][j] * x[j];
        }
    }
#pragma endscop
}
