#include <ap_int.h>
#include <hls_stream.h>
#include <hls_vector.h>
#include <cstring>

/*************************************************
 This file was automatically generated by Sisyphus
*************************************************/

typedef hls::vector<float,16> float16;
typedef hls::vector<float,8> float8;
typedef hls::vector<float,4> float4;
typedef hls::vector<float,2> float2;



void kernel_nlp(float C[80][80], float A[80][60]) {

    int k;
    int j;
    int i;
#pragma scop
    for ( i = 0; i < 80; i++) {
        for ( j = 0; j < i + 1; j++) {
            C[i][j] *= beta;
        }
    }
    for ( i = 0; i < 80; i++) {
        for ( k = 0; k < 60; k++) {
            for ( j = 0; j < i + 1; j++) {
                C[i][j] += alpha * A[i][k] * A[j][k];
            }
        }
    }
#pragma endscop
}
